layout_spectrum: 0.5448028
color:
  saturation: 0.5053763
  lightness: 0.1164875
  brandStrength: 1
  brandColors:
    - '#FFFFFF'
    - '#E23725'
    - '#C1C1C1'
    - '#E05648'
    - '#ED8B80'
  rhythmicContrast: 0.8422939
typography_spectrum: 0.546595
name: ASID California North
